### ISSUE TITLE
no clean output when piped to other commands 

### ISSUE THREAD

**Issue by muralikodali** [madprops/rumsfeld#1]
we can pipe output to other commands, if the given output is clean. 
it adds value to the program.

i have got the below output with `fd` when piped  to vim : 
![screenshot_20220902173611](https://user-images.githubusercontent.com/11482766/188140145-fc415128-da33-4af6-be03-4ee558d0861c.png)

i have got the below output with `rumsfeld` when piped to vim : 
![screenshot_20220902173644](https://user-images.githubusercontent.com/11482766/188140255-e1836489-0e1f-4cbe-ba12-d4eb04cb0580.png)

**Comment by madprops** [comment]
Hey @muralikodali thanks for the issue report. To remedy this I added a check to test if stdout is being piped, and if it is then don't apply formatting. 

`piped: not isatty(stdout)`

In case you need to do it manually I also added a `clean` flag that can be used.

`clean = add_arg(name="clean", kind="flag", help="Print a clean list without formatting", alt="c")`

Piping to `vim -`:

![rumsfeld_vim](https://user-images.githubusercontent.com/206498/188263530-3348d281-bfdc-4c50-a43d-758e26d20042.jpg)

Let me know if this works for you.

**Comment by muralikodali** [comment]
thanks.
this tool is more useful now.
